### ISSUE TITLE
Jenkinsインストールを選択した際にエラーとなる

### ISSUE THREAD

**Issue by ayapapa** [ayapapa/alminium#19]
以下の実行結果でエラーが発生する。
# Now push it to the update URL

curl --noproxy localhost -X POST -H "Accept: application/json" -d @/tmp/default.json http://localhost:8080/jenkins/updateCenter/byId/default/postBack --verbose
エラーログは以下の通り、
- Hostname was NOT found in DNS cache
-   Trying 127.0.0.1...
- Connected to localhost (127.0.0.1) port 8080 (#0)
  > POST /jenkins/updateCenter/byId/default/postBack HTTP/1.1
  > User-Agent: curl/7.35.0
  > Host: localhost:8080
  > Accept: application/json
  > Content-Length: 927387
  > Content-Type: application/x-www-form-urlencoded
  > Expect: 100-continue
  > 
  < HTTP/1.1 500 Server Error
  < X-Content-Type-Options: nosniff
  < Cache-Control: no-cache,no-store,must-revalidate
  < X-Hudson-Theme: default
  < Content-Type: text/html;charset=UTF-8
  < Set-Cookie: JSESSIONID.5dd51670=1ablmxc5ygdlx1qbzrfwwhriq0;Path=/jenkins;HttpOnly
  < Expires: Thu, 01 Jan 1970 00:00:00 GMT
  < X-Hudson: 1.395
  < X-Jenkins: 1.624
  < X-Jenkins-Session: e4e5d268
  < X-Hudson-CLI-Port: 43682
  < X-Jenkins-CLI-Port: 43682
  < X-Jenkins-CLI2-Port: 43682
  < X-Frame-Options: sameorigin
  < X-SSH-Endpoint: localhost:44590
  < X-Instance-Identity: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAhOKxJQGpw+pxNVtewXiHxazfbv3aiW7R+aYyIhGnFLSIAHIG6hO+z+k+2TLXX4fQPml3oNCOQgIaDItaFo59fdO2BumurblDljfMq/+mRNXet1yfmqrwIKQ8CwL+YmTrW3vRroDwzke47CWjM1h2DGhn+6ftMYLbQieMx2WtX8aZXKNFfk/uTb7Emt0aOUY4rf6QAIYEr2bC+KMyeLwY5rtGwU3Chmy12O9Yr5I+kXZWUT3k+lNbekuzB67fZXN0pvgNAPhqcHL9O9jzNZteUyKUpl/bBpZwNcOinSiOSZELssnCzR5h4wXaUkKQ+CU1LMOEf4aezISeI36Gr5iEHQIDAQAB
  < Content-Length: 15231
  < Connection: close
- Server Jetty(winstone-2.8) is not blacklisted
  < Server: Jetty(winstone-2.8)
  < 
  
  <!DOCTYPE html><html><head resURL="/jenkins/static/e4e5d268">
  
  <title>Jenkins [Jenkins]</title><link rel="stylesheet" type="text/css" href="/jenkins/static/e4e5d268/css/style.css" /><link rel="stylesheet" type="text/css" href="/jenkins/static/e4e5d268/css/color.css" /><link rel="stylesheet" type="text/css" href="/jenkins/static/e4e5d268/css/responsive-grid.css" /><link rel="shortcut icon" type="image/vnd.microsoft.icon" href="/jenkins/static/e4e5d268/favicon.ico" /><script>var isRunAsTest=false; var rootURL="/jenkins"; var resURL="/jenkins/static/e4e5d268";</script><script src="/jenkins/static/e4e5d268/scripts/prototype.js" type="text/javascript"></script><script src="/jenkins/static/e4e5d268/scripts/behavior.js" type="text/javascript"></script><script src='/jenkins/adjuncts/e4e5d268/org/kohsuke/stapler/bind.js' type='text/javascript'></script><script src="/jenkins/static/e4e5d268/scripts/yui/yahoo/yahoo-min.js"></script><script src="/jenkins/static/e4e5d268/scripts/yui/dom/dom-min.js"></script><script src="/jenkins/static/e4e5d268/scripts/yui/event/event-min.js"></script><script src="/jenkins/static/e4e5d268/scripts/yui/animation/animation-min.js"></script><script src="/jenkins/static/e4e5d268/scripts/yui/dragdrop/dragdrop-min.js"></script><script src="/jenkins/static/e4e5d268/scripts/yui/container/container-min.js"></script><script src="/jenkins/static/e4e5d268/scripts/yui/connection/connection-min.js"></script><script src="/jenkins/static/e4e5d268/scripts/yui/datasource/datasource-min.js"></script><script src="/jenkins/static/e4e5d268/scripts/yui/autocomplete/autocomplete-min.js"></script><script src="/jenkins/static/e4e5d268/scripts/yui/menu/menu-min.js"></script><script src="/jenkins/static/e4e5d268/scripts/yui/element/element-min.js"></script><script src="/jenkins/static/e4e5d268/scripts/yui/button/button-min.js"></script><script src="/jenkins/static/e4e5d268/scripts/yui/storage/storage-min.js"></script><script src="/jenkins/static/e4e5d268/scripts/hudson-behavior.js" type="text/javascript"></script><script src="/jenkins/static/e4e5d268/scripts/sortable.js" type="text/javascript"></script><script>crumb.init("", "");</script><link rel="stylesheet" type="text/css" href="/jenkins/static/e4e5d268/scripts/yui/container/assets/container.css" /><link rel="stylesheet" type="text/css" href="/jenkins/static/e4e5d268/scripts/yui/assets/skins/sam/skin.css" /><link rel="stylesheet" type="text/css" href="/jenkins/static/e4e5d268/scripts/yui/container/assets/skins/sam/container.css" /><link rel="stylesheet" type="text/css" href="/jenkins/static/e4e5d268/scripts/yui/button/assets/skins/sam/button.css" /><link rel="stylesheet" type="text/css" href="/jenkins/static/e4e5d268/scripts/yui/menu/assets/skins/sam/menu.css" /><link title="Jenkins" rel="search" type="application/opensearchdescription+xml" href="/jenkins/opensearch.xml" /><meta name="ROBOTS" content="INDEX,NOFOLLOW" /><script src="/jenkins/static/e4e5d268/scripts/yui/cookie/cookie-min.js"></script></head><body data-model-type="hudson.model.Hudson" id="jenkins" data-version="jenkins-1.624" class="yui-skin-sam jenkins-1.624"><a href="#skip2content" class="skiplink">Skip to content</a><div id="page-head"><div id="header"><div class="logo"><a id="jenkins-home-link" href="/jenkins/"><img id="jenkins-head-icon" alt="title" src="/jenkins/static/e4e5d268/images/headshot.png" /><img id="jenkins-name-icon" height="34" alt="title" width="139" src="/jenkins/static/e4e5d268/images/title.png" /></a></div><div class="login"> </div><div class="searchbox hidden-xs"><form style="position:relative;" name="search" action="/jenkins/search/" class="no-json" method="get"><div id="search-box-minWidth"></div><div id="search-box-sizer"></div><div id="searchform"><input id="search-box" placeholder="検索" name="q" class="has-default-text" /> <a href="http://wiki.jenkins-ci.org/display/JA/Search+Box"><img style="width: 16px; height: 16px; " class="icon-help icon-sm" src="/jenkins/static/e4e5d268/images/16x16/help.png" /></a><div id="search-box-completion"></div><script>createSearchBox("/jenkins/search/");</script></div></form></div></div><div id="breadcrumbBar"><tr id="top-nav"><td id="left-top-nav" colspan="2"><link rel='stylesheet' href='/jenkins/adjuncts/e4e5d268/lib/layout/breadcrumbs.css' type='text/css' /><script src='/jenkins/adjuncts/e4e5d268/lib/layout/breadcrumbs.js' type='text/javascript'></script><div class="top-sticker noedge"><div class="top-sticker-inner"><div id="right-top-nav"></div><ul id="breadcrumbs"><li class="item"><a class="model-link inside" href="/jenkins/">Jenkins</a></li><li class="children" href="/jenkins/"></li></ul><div id="breadcrumb-menu-target"></div></div></div></td></tr></div></div><div id="page-body"><div id="side-panel"><div class="task"><a class="task-icon-link" href="http://jenkins-ci.org/"><img style="width: 24px; height: 24px; width: 24px; height: 24px; margin: 2px;" class="icon-next icon-md" src="/jenkins/static/e4e5d268/images/24x24/next.png" /></a> <a class="task-link" href="http://jenkins-ci.org/">JenkinsWebサイト</a></div><div class="task"><a class="task-icon-link" href="http://issues.jenkins-ci.org/"><img style="width: 24px; height: 24px; width: 24px; height: 24px; margin: 2px;" class="icon-gear2 icon-md" src="/jenkins/static/e4e5d268/images/24x24/gear2.png" /></a> <a class="task-link" href="http://issues.jenkins-ci.org/">バグ管理システム</a></div><div class="task"><a class="task-icon-link" href="http://jenkins-ci.org/content/mailing-lists"><img style="width: 24px; height: 24px; width: 24px; height: 24px; margin: 2px;" class="icon-search icon-md" src="/jenkins/static/e4e5d268/images/24x24/search.png" /></a> <a class="task-link" href="http://jenkins-ci.org/content/mailing-lists">メーリングリスト</a></div><div class="task"><a class="task-icon-link" href="https://twitter.com/jenkinsci"><img style="width: 24px; height: 24px; width: 24px; height: 24px; margin: 2px;" class="icon-user icon-md" src="/jenkins/static/e4e5d268/images/24x24/user.png" /></a> <a class="task-link" href="https://twitter.com/jenkinsci">Twitter: @jenkinsci</a></div></div><div id="main-panel"><a name="skip2content"></a><h1 style="text-align: center"><img height="179" width="154" src="/jenkins/static/e4e5d268/images/rage.png" /><span style="font-size:50px"> Oops!</span></h1><div id="error-description"><p>リクエスト処理中に問題が発生しました。
      <a href="https://issues.jenkins-ci.org/">バグ管理システム</a>をチェックして、同じような問題が報告されていないか確認してください。
      報告済みであれば、投票(vote)してコメントしてください。そうすれば、その問題の影響の大きさが開発者に伝わります。
      もし、報告されていない問題であれば、チケットを登録してください。
      チケットを登録するときには、Jenkinsと関連するプラグインのバージョンとあわせて、必ずスタックトレースをすべて添付しください。
      何が起きたのか理解するには、<a href="http://jenkins-ci.org/content/mailing-lists">メーリングリスト</a>が参考になります。</p><h2>スタックトレース</h2><pre style="margin:2em; clear:both">javax.servlet.ServletException: org.acegisecurity.AccessDeniedException: browser-based download disabled
  at org.kohsuke.stapler.Stapler.tryInvoke(Stapler.java:796)
  at org.kohsuke.stapler.Stapler.invoke(Stapler.java:876)
  at org.kohsuke.stapler.MetaClass$6.doDispatch(MetaClass.java:249)
  at org.kohsuke.stapler.NameBasedDispatcher.dispatch(NameBasedDispatcher.java:53)
  at org.kohsuke.stapler.Stapler.tryInvoke(Stapler.java:746)
  at org.kohsuke.stapler.Stapler.invoke(Stapler.java:876)
  at org.kohsuke.stapler.MetaClass$4.doDispatch(MetaClass.java:211)
  at org.kohsuke.stapler.NameBasedDispatcher.dispatch(NameBasedDispatcher.java:53)
  at org.kohsuke.stapler.Stapler.tryInvoke(Stapler.java:746)
  at org.kohsuke.stapler.Stapler.invoke(Stapler.java:876)
  at org.kohsuke.stapler.Stapler.invoke(Stapler.java:649)
  at org.kohsuke.stapler.Stapler.service(Stapler.java:238)
  at javax.servlet.http.HttpServlet.service(HttpServlet.java:848)
  at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:686)
  at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1494)
  at hudson.util.PluginServletFilter$1.doFilter(PluginServletFilter.java:132)
  at hudson.util.PluginServletFilter.doFilter(PluginServletFilter.java:123)
  at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1482)
  at hudson.security.csrf.CrumbFilter.doFilter(CrumbFilter.java:49)
  at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1482)
  at org.jenkinsci.plugins.reverse_proxy_auth.ReverseProxySecurityRealm$1.doFilter(ReverseProxySecurityRealm.java:468)
  at hudson.security.HudsonFilter.doFilter(HudsonFilter.java:171)
  at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1482)
  at org.kohsuke.stapler.compression.CompressionFilter.doFilter(CompressionFilter.java:49)
  at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1482)
  at hudson.util.CharacterEncodingFilter.doFilter(CharacterEncodingFilter.java:81)
  at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1482)
  at org.kohsuke.stapler.DiagnosticThreadNameFilter.doFilter(DiagnosticThreadNameFilter.java:30)
  at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1474)
  at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:499)
  at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:137)
  at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:533)
  at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:231)
  at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1086)
  at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:428)
  at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:193)
  at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1020)
  at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:135)
  at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:116)
  at org.eclipse.jetty.server.Server.handle(Server.java:370)
  at org.eclipse.jetty.server.AbstractHttpConnection.handleRequest(AbstractHttpConnection.java:489)
  at org.eclipse.jetty.server.AbstractHttpConnection.headerComplete(AbstractHttpConnection.java:949)
  at org.eclipse.jetty.server.AbstractHttpConnection$RequestHandler.headerComplete(AbstractHttpConnection.java:1011)
  at org.eclipse.jetty.http.HttpParser.parseNext(HttpParser.java:651)
  at org.eclipse.jetty.http.HttpParser.parseAvailable(HttpParser.java:235)
  at org.eclipse.jetty.server.AsyncHttpConnection.handle(AsyncHttpConnection.java:82)
  at org.eclipse.jetty.io.nio.SelectChannelEndPoint.handle(SelectChannelEndPoint.java:668)
  at org.eclipse.jetty.io.nio.SelectChannelEndPoint$1.run(SelectChannelEndPoint.java:52)
  at winstone.BoundedExecutorService$1.run(BoundedExecutorService.java:77)
  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
  at java.lang.Thread.run(Thread.java:745)
  Caused by: org.acegisecurity.AccessDeniedException: browser-based download disabled
  at jenkins.model.DownloadSettings.checkPostBackAccess(DownloadSettings.java:85)
  at hudson.model.UpdateSite.doPostBack(UpdateSite.java:177)
  at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
  at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  at java.lang.reflect.Method.invoke(Method.java:606)
  at org.kohsuke.stapler.Function$InstanceFunction.invoke(Function.java:298)
  at org.kohsuke.stapler.Function.bindAndInvoke(Function.java:161)
  at org.kohsuke.stapler.Function.bindAndInvokeAndServeResponse(Function.java:96)
  at org.kohsuke.stapler.MetaClass$1.doDispatch(MetaClass.java:121)
  at org.kohsuke.stapler.NameBasedDispatcher.dispatch(NameBasedDispatcher.java:53)
  at org.kohsuke.stapler.Stapler.tryInvoke(Stapler.java:746)
  ... 51 more
  </pre></div></div></div><footer><div class="container-fluid"><div class="row"><div class="col-md-6" id="footer"></div><div class="col-md-18"><span class="page_generated">ページ更新時: 2015/08/16 14:06:50</span><span class="rest_api"><a href="api/">REST API</a></span><span class="jenkins_ver"><a href="http://jenkins-ci.org/">Jenkins ver. 1.624</a></span><script>Behaviour.addLoadEvent(function() {
      loadScript("http://usage.jenkins-ci.org/usage-stats.js?R+JCH3bb1cclgizzFk2s43/ocnp4bJJ2xc7Zi6u2euCk59CuNKvfXhhbdtOQrB9Do3EReS0uaBBqVw3G1yMk0xuzSAWTlvDqcbYDn6qSVR6dullRrVzxZ5MtTEezOaR+V5ot6C9Sz9XZOxyoBJki5Y/sbze0eIVlfR8hx6xuUjhqX2uS2sfD9BfU3AsLYH9bJr2N4SqRTjhXOh8Vu7gJUIq8yRK5xRcS0GSifWRmc+HnedLrkIvVnzMeb32BGmjicrioP1kHiUH2+nfnBbPO6afrAE7jTgSpNkbjHazZNRFLNZcTHdl7ydee/lEs+YAIvUDeSA6lvt0cCdAEyzNWOf9Oc+UFoLRcUztxxRYcDrFJ2VDIJ2hHBIx7jT9tDEsKTLh4SAlHyJonYaoZrr5iQe8Dt5gIUakf8a7UQFiySUNWNlsOQsGhQhPmz100JubYP8IDYTwBceTlr4/yVYih1iVSEIPf5FY/rvYnnCPM1MUIKhaBJ59mHncDCrsyQE4Wru/EqAWzu7kVG4UVkY1CrSl1376OXE7LPg3j5u7R0DVd6gGKJRo5qeZj+q7+xLG9QBmx3MHryCWZu8ZF3GfMGxR8SJMq3A0vkIpoEdDDCy7xrznzyiiRNI/NZkmKh7QR8tjkeLn9PmqRpB/lIM3AZomrnItorOgukqcLr9JWK5gSxAGf1DhRlVWP52vk9+fukQDzB3CnglrZak7Ll0awfTcCDFD4NSHvwXI+SHExQwv1fqBKxEWwWp85xfzuDIngD8YxptfbyTVUUwluHbOvWKzZ83ovhdjGYGc/4mI6LlLyueU6rP1bs5A7+GuYlW0yvHYWGWN6AffcLTrBmZJX1QBQUJ+D8v/+PvoGxvTIcH8gvXKs3UiEPu/FO9RUc7N6TgOWOj1FUaSvHicXtcNq8OlYML/rz/8Kazr/Ju4cnkT6FAHqqZdf28M3sdBZcmWc");
    });</script><div id="l10n-dialog" class="dialog"></div><div id="l10n-footer" style="display:none; float:left"><a href="#" onclick="return showTranslationDialog();"><img src="/jenkins/static/e4e5d268/plugin/translation/flags.png" />
    Help us localize this page
  </a></div><script>var footer = document.getElementById('l10n-footer');
  var f = document.getElementById('footer');
  f.insertBefore(footer,f.firstChild);
  footer.style.display="block";
  
  var translation={}; 
  translation.bundles = "su5/3BlxBXBZh2hAyWgyEZt1CvaGwx8LmVnDeD5lUUIA2ZupcYcalE1d5B5EUeWFRqpJr+HFHYCoLS2i4bjQ3orAZEiCtLaMrum/5LtaweRZMEg3cq0WJt+s6EpLALgmKeerI70aip074Yk3RM4t1yZTJP/k2uOuR+54YNfA+vfVHDO+aaHueE/gtLr721SvjYcLhaP7UejOpeR9PZ/emty/FM8LuzUtf8GWcyHPM7uLVUS1m+YbSfwT9xg+Dxf9etQecWHl2zPsGGdW0IGXNjXbL18UuO86tfWO89if6FFO1MM/fl6ssduMOFFF69dGNGNR/08c30YR94vbnXMRpxzkJTTH9MVim5Yo8HgxfBNNex1X0XFYwAxjEhn1qvj8Yuu3hAiQXKqDUkW03+9XolwZQUK27WbjNk4QIHana6DU2pEY0Pi2G5dnj958uvkO";
  translation.detectedLocale = "";
  
  function showTranslationDialog() {
    if(!translation.launchDialog)
      loadScript("/jenkins/static/e4e5d268/plugin/translation/dialog.js");
    else
      translation.launchDialog();
    return false; 
- Closing connection 0

**Comment by ayapapa** [comment]
アクセス制限が強化された可能性があるため、問題となるコマンドはコメントアウトし、
default.json
を、
/var/lib/jenkins/updates/
にコピーしjenkinsを再起動する方式にする。
参考：https://gist.github.com/rowan-m/1026918#file-gistfile1-txt
