### ISSUE TITLE
jenkinsのインストールが失敗する

### ISSUE THREAD

**Issue by ayapapa** [ayapapa/alminium#64]
エラーログ：
java.io.IOException: No X-Jenkins-CLI2-Port among [null, X-Required-Permission, X-Jenkins, X-You-Are-In-Group, X-Hudson, Content-Length, Expires, X-You-Are-Authenticated-As, X-Permission-Implied-By, Set-Cookie, Server, X-Content-Type-Options, Date, X-Jenkins-Session, Content-Type]
        at hudson.cli.CLI.getCliTcpPort(CLI.java:290)
        at hudson.cli.CLI.<init>(CLI.java:128)
        at hudson.cli.CLIConnectionFactory.connect(CLIConnectionFactory.java:72)
        at hudson.cli.CLI._main(CLI.java:479)
        at hudson.cli.CLI.main(CLI.java:390)
        Suppressed: java.io.IOException: Server returned HTTP response code: 403 for URL: http://localhost:8080/jenkins/cli
                at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1628)
                at hudson.cli.FullDuplexHttpStream.<init>(FullDuplexHttpStream.java:78)
                at hudson.cli.CLI.connectViaHttp(CLI.java:158)
                at hudson.cli.CLI.<init>(CLI.java:132)
                ... 3 more

**Comment by ayapapa** [comment]
一時的に、Jenkinsインストールをする場合は手動でインストールするようにスクリプトを変更(commit 6ce2d63dc97ccd0966b303e78c6ad72397d20856)。本変更は恒久策後再変更予定。

**Comment by ayapapa** [comment]
Jenkins2.0がリリースされた時点で、ALMiniumインストール時にJenkins2.0がインストールされるようになった。
Jenkin2.0の仕様に合わせた変更が必要（初期起動時はウィザードが起動するためその無効化が必要）

**Comment by ayapapa** [comment]
とりあえず、Jenkins1.xでインストールできるようにする。
（2.xへは、手動でアップグレードできる）
